event_planner.settings:
  type: config_object
  label: 'Event Planner settings'
  mapping:
    admin_notification_email:
      type: email
      label: 'Administrator notification email'
    notify_admin:
      type: boolean
      label: 'Notify administrator'
